"""Add idempotency fields to Document

Revision ID: 6f2e1ba0899d
Revises: d425e108d4a5
Create Date: 2026-05-19 14:50:49.854971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2e1ba0899d'
down_revision: Union[str, Sequence[str], None] = 'd425e108d4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_notified', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('notified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'notified_at')
    op.drop_column('documents', 'is_notified')
    # ### end Alembic commands ###
