"""add last_checked_at to companies

Revision ID: d425e108d4a5
Revises: 2a0eb9fc7cc5
Create Date: 2026-05-13 15:46:27.099287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd425e108d4a5'
down_revision: Union[str, Sequence[str], None] = '2a0eb9fc7cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'last_checked_at')
    # ### end Alembic commands ###
